#index:
#    path: /
#    controller: App\Controller\DefaultController::index

lucky2_methode_toto:
  path:   /lucky2/{slug}  
  controller: App\Controller\Lucky2Controller::toto


lucky2_methode_tata:
  path:     /lucky2/{year}/{slug}.{_format}
  controller: App\Controller\Lucky2Controller::tata
  defaults:
      _format: html
  requirements:
      _format:  html|rss
      year:     \d+
      
