# Les routes définissent l'url de la page (path) et le controller à appeler 

#index:
#    path: /
#    controller: App\Controller\DefaultController::index

<<<<<<< HEAD
my_appli_lucky_number:
    path: /lucky1
    controller: App\Controller\Lucky1Controller::number
=======
lucky2_methode_titi:
  path: /                                                 # alias de l'url
  controller: App\Controller\Luck2Controller::titi        # nom du controller et methode vers laquelle pointe l'url   
    
lucky2_methode_toto:
  path: /lucky2/{slug}  
  controller: App\Controller\Lucky2Controller::toto


lucky2_methode_tata:
  path: /lucky2/{year}/{slug}.{_format}
  controller: App\Controller\Lucky2Controller::tata
  defaults:
      _format: html
  requirements:
      _format:  html|rss
      year:     \d+
      
lucky2_methode_number:
  path: /lucky2/number/{max}  
  controller: App\Controller\Lucky2Controller::number      
      
>>>>>>> refs/heads/master
